// Psychoactive Substances Documentation - Auto-Generated Export File

// Re-export types
export type {
  Substance,
  SubstanceCategory,
  CategoryInfo,
  RouteDosageDuration
} from '../types';

// Re-export individual substances
export {
  _1_3_butanediol,
  _1p_eth_lad,
  _1cp_mipla,
  _1cp_al_lad,
  _1b_lsd,
  _1cp_lsd,
  _2_5_dma,
  _1v_lsd,
  _1p_lsd,
  _25c_nbome,
  _25c_nboh,
  _25d_nbome,
  _25b_nbome,
  _25i_nboh,
  _25i_nbome,
  _2c_b_fly,
  _2c_c,
  _2c_d,
  _25n_nbome,
  _2c_b,
  _2c_e,
  _2c_p,
  _2c_i,
  _2c_t,
  _2c_t_21,
  _2c_t_2,
  _2c_t_7,
  _3c_p,
  _3c_e,
  _4_aco_det,
  _4_aco_met,
  _4_aco_dmt,
  _4_aco_dipt,
  _4_aco_mipt,
  _4_ho_det,
  _4_ho_dpt,
  _4_ho_met,
  _4_ho_dipt,
  _4_ho_ept,
  _4_ho_mpt,
  _4_ho_mipt,
  _5_meo_dalt,
  _5_meo_dibf,
  _5_meo_dipt,
  _5_meo_dmt,
  _5_meo_mipt,
  _6_apb,
  al_lad,
  ald_52,
  allylescaline,
  ayahuasca,
  bufotenin,
  bromo_dragonfly,
  det,
  dob,
  dmt,
  doc,
  dom,
  doi,
  dpt,
  dipt,
  ept,
  eth_lad,
  efavirenz,
  escaline,
  ibogaine,
  lae_32,
  lsm_775,
  lsa,
  lsz,
  lsd,
  mpt,
  met,
  mda,
  methallylescaline,
  mescaline,
  mipt,
  mipla,
  pargy_lad,
  pro_lad,
  _2_aminoindane,
  _2_fea,
  _2_fa,
  _2_fma,
  _3_4_ctmp,
  _3_fa,
  _3_fpm,
  _3_fma,
  _3_fea,
  _3_mmc,
  _4_fa,
  _4_fma,
  _4f_eph,
  _4f_mph,
  _5_apb,
  _6_apdb,
  a_php,
  a_pvp,
  adrafinil,
  amphetamine,
  armodafinil,
  benzydamine,
  bromantane,
  butylone,
  caffeine,
  cyclazodone,
  cocaine,
  desoxypipradrol,
  dextroamphetamine,
  dichloropane,
  eth_cat,
  ephedrine,
  ephylone,
  ethylphenidate,
  ethylone,
  fenethylline,
  hexedrone,
  isopropylphenidate,
  kratom,
  lisdexamfetamine,
  mcpp,
  mdpv,
  mdma,
  mephedrone,
  methcathinone,
  methamphetamine,
  methiopropamine,
  methylone,
  methylnaphthidate,
  methylphenidate,
  mexedrone,
  modafinil,
  n_methylbisfluoromodafinil,
  n_ethylhexedrone,
  nm_2_ai,
  nep,
  nicotine,
  oxiracetam,
  pentedrone,
  phenylpiracetam,
  _1_4_butanediol,
  _2m2b,
  alcohol,
  alprazolam,
  baclofen,
  cake,
  carisoprodol,
  clonazepam,
  clonidine,
  clonazolam,
  deschloroetizolam,
  diazepam,
  diclazepam,
  eszopiclone,
  etizolam,
  f_phenibut,
  flubromazepam,
  flualprazolam,
  flunitrazepam,
  flubromazolam,
  flunitrazolam,
  gbl,
  ghb,
  grayanotoxin,
  gabapentin,
  gaboxadol,
  lorazepam,
  mephenaqualone,
  methaqualone,
  metizolam,
  midazolam,
  mirtazapine,
  nifoxipam,
  pentobarbital,
  phenobarbital,
  _2_fluorodeschloroketamine,
  _3_ho_pce,
  _3_ho_pcp,
  _3_meo_pcmo,
  _3_meo_pce,
  _3_meo_pcp,
  _4_meo_pcp,
  deschloroketamine,
  dextromethorphan,
  diphenidine,
  ephenidine,
  hxe,
  ketamine,
  mxipr,
  memantine,
  methoxetamine,
  methoxphenidine,
  nitrous,
  o_pce,
  pce,
  pcp,
  _5_mapb,
  mdai,
  mdea,
  pma,
  pmma,
  _5f_akb48,
  _5f_pb_22,
  ab_fubinaca,
  apica,
  cannabidiol,
  jwh_018,
  jwh_073,
  acetylfentanyl,
  buprenorphine,
  codeine,
  desomorphine,
  dextropropoxyphene,
  dihydrocodeine,
  ethylmorphine,
  fentanyl,
  hydrocodone,
  hydromorphone,
  heroin,
  methadone,
  morphine,
  naloxone,
  o_desmethyltramadol,
  oxycodone,
  oxymorphone,
  pethidine,
  datura,
  diphenhydramine,
  myristicin,
  _5_hydroxytryptophan,
  alpha_gpc,
  aniracetam,
  citicoline,
  choline_bitartrate,
  creatine,
  coluracetam,
  galantamine,
  meclofenoxate,
  n_acetylcysteine,
  omberacetam,
  blue_lotus,
  bromazepam,
  cannabis
} from './substances';

// Import for helper functions
import { Substance, SubstanceCategory } from '../types';
import {
  _1_3_butanediol,
  _1p_eth_lad,
  _1cp_mipla,
  _1cp_al_lad,
  _1b_lsd,
  _1cp_lsd,
  _2_5_dma,
  _1v_lsd,
  _1p_lsd,
  _25c_nbome,
  _25c_nboh,
  _25d_nbome,
  _25b_nbome,
  _25i_nboh,
  _25i_nbome,
  _2c_b_fly,
  _2c_c,
  _2c_d,
  _25n_nbome,
  _2c_b,
  _2c_e,
  _2c_p,
  _2c_i,
  _2c_t,
  _2c_t_21,
  _2c_t_2,
  _2c_t_7,
  _3c_p,
  _3c_e,
  _4_aco_det,
  _4_aco_met,
  _4_aco_dmt,
  _4_aco_dipt,
  _4_aco_mipt,
  _4_ho_det,
  _4_ho_dpt,
  _4_ho_met,
  _4_ho_dipt,
  _4_ho_ept,
  _4_ho_mpt,
  _4_ho_mipt,
  _5_meo_dalt,
  _5_meo_dibf,
  _5_meo_dipt,
  _5_meo_dmt,
  _5_meo_mipt,
  _6_apb,
  al_lad,
  ald_52,
  allylescaline,
  ayahuasca,
  bufotenin,
  bromo_dragonfly,
  det,
  dob,
  dmt,
  doc,
  dom,
  doi,
  dpt,
  dipt,
  ept,
  eth_lad,
  efavirenz,
  escaline,
  ibogaine,
  lae_32,
  lsm_775,
  lsa,
  lsz,
  lsd,
  mpt,
  met,
  mda,
  methallylescaline,
  mescaline,
  mipt,
  mipla,
  pargy_lad,
  pro_lad,
  _2_aminoindane,
  _2_fea,
  _2_fa,
  _2_fma,
  _3_4_ctmp,
  _3_fa,
  _3_fpm,
  _3_fma,
  _3_fea,
  _3_mmc,
  _4_fa,
  _4_fma,
  _4f_eph,
  _4f_mph,
  _5_apb,
  _6_apdb,
  a_php,
  a_pvp,
  adrafinil,
  amphetamine,
  armodafinil,
  benzydamine,
  bromantane,
  butylone,
  caffeine,
  cyclazodone,
  cocaine,
  desoxypipradrol,
  dextroamphetamine,
  dichloropane,
  eth_cat,
  ephedrine,
  ephylone,
  ethylphenidate,
  ethylone,
  fenethylline,
  hexedrone,
  isopropylphenidate,
  kratom,
  lisdexamfetamine,
  mcpp,
  mdpv,
  mdma,
  mephedrone,
  methcathinone,
  methamphetamine,
  methiopropamine,
  methylone,
  methylnaphthidate,
  methylphenidate,
  mexedrone,
  modafinil,
  n_methylbisfluoromodafinil,
  n_ethylhexedrone,
  nm_2_ai,
  nep,
  nicotine,
  oxiracetam,
  pentedrone,
  phenylpiracetam,
  _1_4_butanediol,
  _2m2b,
  alcohol,
  alprazolam,
  baclofen,
  cake,
  carisoprodol,
  clonazepam,
  clonidine,
  clonazolam,
  deschloroetizolam,
  diazepam,
  diclazepam,
  eszopiclone,
  etizolam,
  f_phenibut,
  flubromazepam,
  flualprazolam,
  flunitrazepam,
  flubromazolam,
  flunitrazolam,
  gbl,
  ghb,
  grayanotoxin,
  gabapentin,
  gaboxadol,
  lorazepam,
  mephenaqualone,
  methaqualone,
  metizolam,
  midazolam,
  mirtazapine,
  nifoxipam,
  pentobarbital,
  phenobarbital,
  _2_fluorodeschloroketamine,
  _3_ho_pce,
  _3_ho_pcp,
  _3_meo_pcmo,
  _3_meo_pce,
  _3_meo_pcp,
  _4_meo_pcp,
  deschloroketamine,
  dextromethorphan,
  diphenidine,
  ephenidine,
  hxe,
  ketamine,
  mxipr,
  memantine,
  methoxetamine,
  methoxphenidine,
  nitrous,
  o_pce,
  pce,
  pcp,
  _5_mapb,
  mdai,
  mdea,
  pma,
  pmma,
  _5f_akb48,
  _5f_pb_22,
  ab_fubinaca,
  apica,
  cannabidiol,
  jwh_018,
  jwh_073,
  acetylfentanyl,
  buprenorphine,
  codeine,
  desomorphine,
  dextropropoxyphene,
  dihydrocodeine,
  ethylmorphine,
  fentanyl,
  hydrocodone,
  hydromorphone,
  heroin,
  methadone,
  morphine,
  naloxone,
  o_desmethyltramadol,
  oxycodone,
  oxymorphone,
  pethidine,
  datura,
  diphenhydramine,
  myristicin,
  _5_hydroxytryptophan,
  alpha_gpc,
  aniracetam,
  citicoline,
  choline_bitartrate,
  creatine,
  coluracetam,
  galantamine,
  meclofenoxate,
  n_acetylcysteine,
  omberacetam,
  blue_lotus,
  bromazepam,
  cannabis
} from './substances';

// All substances combined into a single array
export const substances: Substance[] = [
  _1_3_butanediol,
  _1p_eth_lad,
  _1cp_mipla,
  _1cp_al_lad,
  _1b_lsd,
  _1cp_lsd,
  _2_5_dma,
  _1v_lsd,
  _1p_lsd,
  _25c_nbome,
  _25c_nboh,
  _25d_nbome,
  _25b_nbome,
  _25i_nboh,
  _25i_nbome,
  _2c_b_fly,
  _2c_c,
  _2c_d,
  _25n_nbome,
  _2c_b,
  _2c_e,
  _2c_p,
  _2c_i,
  _2c_t,
  _2c_t_21,
  _2c_t_2,
  _2c_t_7,
  _3c_p,
  _3c_e,
  _4_aco_det,
  _4_aco_met,
  _4_aco_dmt,
  _4_aco_dipt,
  _4_aco_mipt,
  _4_ho_det,
  _4_ho_dpt,
  _4_ho_met,
  _4_ho_dipt,
  _4_ho_ept,
  _4_ho_mpt,
  _4_ho_mipt,
  _5_meo_dalt,
  _5_meo_dibf,
  _5_meo_dipt,
  _5_meo_dmt,
  _5_meo_mipt,
  _6_apb,
  al_lad,
  ald_52,
  allylescaline,
  ayahuasca,
  bufotenin,
  bromo_dragonfly,
  det,
  dob,
  dmt,
  doc,
  dom,
  doi,
  dpt,
  dipt,
  ept,
  eth_lad,
  efavirenz,
  escaline,
  ibogaine,
  lae_32,
  lsm_775,
  lsa,
  lsz,
  lsd,
  mpt,
  met,
  mda,
  methallylescaline,
  mescaline,
  mipt,
  mipla,
  pargy_lad,
  pro_lad,
  _2_aminoindane,
  _2_fea,
  _2_fa,
  _2_fma,
  _3_4_ctmp,
  _3_fa,
  _3_fpm,
  _3_fma,
  _3_fea,
  _3_mmc,
  _4_fa,
  _4_fma,
  _4f_eph,
  _4f_mph,
  _5_apb,
  _6_apdb,
  a_php,
  a_pvp,
  adrafinil,
  amphetamine,
  armodafinil,
  benzydamine,
  bromantane,
  butylone,
  caffeine,
  cyclazodone,
  cocaine,
  desoxypipradrol,
  dextroamphetamine,
  dichloropane,
  eth_cat,
  ephedrine,
  ephylone,
  ethylphenidate,
  ethylone,
  fenethylline,
  hexedrone,
  isopropylphenidate,
  kratom,
  lisdexamfetamine,
  mcpp,
  mdpv,
  mdma,
  mephedrone,
  methcathinone,
  methamphetamine,
  methiopropamine,
  methylone,
  methylnaphthidate,
  methylphenidate,
  mexedrone,
  modafinil,
  n_methylbisfluoromodafinil,
  n_ethylhexedrone,
  nm_2_ai,
  nep,
  nicotine,
  oxiracetam,
  pentedrone,
  phenylpiracetam,
  _1_4_butanediol,
  _2m2b,
  alcohol,
  alprazolam,
  baclofen,
  cake,
  carisoprodol,
  clonazepam,
  clonidine,
  clonazolam,
  deschloroetizolam,
  diazepam,
  diclazepam,
  eszopiclone,
  etizolam,
  f_phenibut,
  flubromazepam,
  flualprazolam,
  flunitrazepam,
  flubromazolam,
  flunitrazolam,
  gbl,
  ghb,
  grayanotoxin,
  gabapentin,
  gaboxadol,
  lorazepam,
  mephenaqualone,
  methaqualone,
  metizolam,
  midazolam,
  mirtazapine,
  nifoxipam,
  pentobarbital,
  phenobarbital,
  _2_fluorodeschloroketamine,
  _3_ho_pce,
  _3_ho_pcp,
  _3_meo_pcmo,
  _3_meo_pce,
  _3_meo_pcp,
  _4_meo_pcp,
  deschloroketamine,
  dextromethorphan,
  diphenidine,
  ephenidine,
  hxe,
  ketamine,
  mxipr,
  memantine,
  methoxetamine,
  methoxphenidine,
  nitrous,
  o_pce,
  pce,
  pcp,
  _5_mapb,
  mdai,
  mdea,
  pma,
  pmma,
  _5f_akb48,
  _5f_pb_22,
  ab_fubinaca,
  apica,
  cannabidiol,
  jwh_018,
  jwh_073,
  acetylfentanyl,
  buprenorphine,
  codeine,
  desomorphine,
  dextropropoxyphene,
  dihydrocodeine,
  ethylmorphine,
  fentanyl,
  hydrocodone,
  hydromorphone,
  heroin,
  methadone,
  morphine,
  naloxone,
  o_desmethyltramadol,
  oxycodone,
  oxymorphone,
  pethidine,
  datura,
  diphenhydramine,
  myristicin,
  _5_hydroxytryptophan,
  alpha_gpc,
  aniracetam,
  citicoline,
  choline_bitartrate,
  creatine,
  coluracetam,
  galantamine,
  meclofenoxate,
  n_acetylcysteine,
  omberacetam,
  blue_lotus,
  bromazepam,
  cannabis
];

// Map for quick category lookup
const substancesByCategory: Record<string, Substance[]> = {
  'cannabinoids': [
    _5f_akb48,
    _5f_pb_22,
    ab_fubinaca,
    apica,
    cannabidiol,
    jwh_018,
    jwh_073
  ],
  'deliriants': [
    benzydamine,
    mirtazapine,
    datura,
    diphenhydramine,
    myristicin
  ],
  'depressants': [
    nicotine,
    _1_4_butanediol,
    _2m2b,
    alcohol,
    alprazolam,
    baclofen,
    cake,
    carisoprodol,
    clonazepam,
    clonidine,
    clonazolam,
    deschloroetizolam,
    diazepam,
    diclazepam,
    eszopiclone,
    etizolam,
    f_phenibut,
    flubromazepam,
    flualprazolam,
    flunitrazepam,
    flubromazolam,
    flunitrazolam,
    gbl,
    ghb,
    grayanotoxin,
    gabapentin,
    gaboxadol,
    lorazepam,
    mephenaqualone,
    methaqualone,
    metizolam,
    midazolam,
    mirtazapine,
    nifoxipam,
    pentobarbital,
    phenobarbital
  ],
  'dissociatives': [
    _2_fluorodeschloroketamine,
    _3_ho_pce,
    _3_ho_pcp,
    _3_meo_pcmo,
    _3_meo_pce,
    _3_meo_pcp,
    _4_meo_pcp,
    deschloroketamine,
    dextromethorphan,
    diphenidine,
    ephenidine,
    hxe,
    ketamine,
    mxipr,
    memantine,
    methoxetamine,
    methoxphenidine,
    nitrous,
    o_pce,
    pce,
    pcp
  ],
  'empathogens': [
    _5_meo_mipt,
    _6_apb,
    mda,
    _2_fea,
    _3_fma,
    _3_fea,
    _3_mmc,
    _4_fa,
    _4_fma,
    _5_apb,
    _6_apdb,
    butylone,
    ephylone,
    mdpv,
    mdma,
    mephedrone,
    methcathinone,
    methylone,
    _5_mapb,
    mdai,
    mdea,
    pma,
    pmma
  ],
  'hallucinogens': [
    _1_3_butanediol,
    _1p_eth_lad,
    _1cp_mipla,
    _1cp_al_lad,
    _1b_lsd,
    _1cp_lsd,
    _2_5_dma,
    _1v_lsd,
    _1p_lsd,
    _25c_nbome,
    _25c_nboh,
    _25d_nbome,
    _25b_nbome,
    _25i_nboh,
    _25i_nbome,
    _2c_b_fly,
    _2c_c,
    _2c_d,
    _25n_nbome,
    _2c_b,
    _2c_e,
    _2c_p,
    _2c_i,
    _2c_t,
    _2c_t_21,
    _2c_t_2,
    _2c_t_7,
    _3c_p,
    _3c_e,
    _4_aco_det,
    _4_aco_met,
    _4_aco_dmt,
    _4_aco_dipt,
    _4_aco_mipt,
    _4_ho_det,
    _4_ho_dpt,
    _4_ho_met,
    _4_ho_dipt,
    _4_ho_ept,
    _4_ho_mpt,
    _4_ho_mipt,
    _5_meo_dalt,
    _5_meo_dibf,
    _5_meo_dipt,
    _5_meo_dmt,
    _5_meo_mipt,
    _6_apb,
    al_lad,
    ald_52,
    allylescaline,
    ayahuasca,
    bufotenin,
    bromo_dragonfly,
    det,
    dob,
    dmt,
    doc,
    dom,
    doi,
    dpt,
    dipt,
    ept,
    eth_lad,
    efavirenz,
    escaline,
    ibogaine,
    lae_32,
    lsm_775,
    lsa,
    lsz,
    lsd,
    mpt,
    met,
    mda,
    methallylescaline,
    mescaline,
    mipt,
    mipla,
    pargy_lad,
    pro_lad
  ],
  'nootropics': [
    adrafinil,
    bromantane,
    n_methylbisfluoromodafinil,
    oxiracetam,
    phenylpiracetam,
    _5_hydroxytryptophan,
    alpha_gpc,
    aniracetam,
    citicoline,
    choline_bitartrate,
    creatine,
    coluracetam,
    galantamine,
    meclofenoxate,
    n_acetylcysteine,
    omberacetam
  ],
  'opioids': [
    kratom,
    acetylfentanyl,
    buprenorphine,
    codeine,
    desomorphine,
    dextropropoxyphene,
    dihydrocodeine,
    ethylmorphine,
    fentanyl,
    hydrocodone,
    hydromorphone,
    heroin,
    methadone,
    morphine,
    naloxone,
    o_desmethyltramadol,
    oxycodone,
    oxymorphone,
    pethidine
  ],
  'other': [
    blue_lotus,
    bromazepam,
    cannabis
  ],
  'stimulants': [
    _2_5_dma,
    mda,
    _2_aminoindane,
    _2_fea,
    _2_fa,
    _2_fma,
    _3_4_ctmp,
    _3_fa,
    _3_fpm,
    _3_fma,
    _3_fea,
    _3_mmc,
    _4_fa,
    _4_fma,
    _4f_eph,
    _4f_mph,
    _5_apb,
    _6_apdb,
    a_php,
    a_pvp,
    adrafinil,
    amphetamine,
    armodafinil,
    benzydamine,
    bromantane,
    butylone,
    caffeine,
    cyclazodone,
    cocaine,
    desoxypipradrol,
    dextroamphetamine,
    dichloropane,
    eth_cat,
    ephedrine,
    ephylone,
    ethylphenidate,
    ethylone,
    fenethylline,
    hexedrone,
    isopropylphenidate,
    kratom,
    lisdexamfetamine,
    mcpp,
    mdpv,
    mdma,
    mephedrone,
    methcathinone,
    methamphetamine,
    methiopropamine,
    methylone,
    methylnaphthidate,
    methylphenidate,
    mexedrone,
    modafinil,
    n_methylbisfluoromodafinil,
    n_ethylhexedrone,
    nm_2_ai,
    nep,
    nicotine,
    oxiracetam,
    pentedrone,
    phenylpiracetam
  ]
};

// Map for quick ID lookup
const substancesById: Record<string, Substance> = {
  '1-3-butanediol': _1_3_butanediol,
  '1p-eth-lad': _1p_eth_lad,
  '1cp-mipla': _1cp_mipla,
  '1cp-al-lad': _1cp_al_lad,
  '1b-lsd': _1b_lsd,
  '1cp-lsd': _1cp_lsd,
  '2-5-dma': _2_5_dma,
  '1v-lsd': _1v_lsd,
  '1p-lsd': _1p_lsd,
  '25c-nbome': _25c_nbome,
  '25c-nboh': _25c_nboh,
  '25d-nbome': _25d_nbome,
  '25b-nbome': _25b_nbome,
  '25i-nboh': _25i_nboh,
  '25i-nbome': _25i_nbome,
  '2c-b-fly': _2c_b_fly,
  '2c-c': _2c_c,
  '2c-d': _2c_d,
  '25n-nbome': _25n_nbome,
  '2c-b': _2c_b,
  '2c-e': _2c_e,
  '2c-p': _2c_p,
  '2c-i': _2c_i,
  '2c-t': _2c_t,
  '2c-t-21': _2c_t_21,
  '2c-t-2': _2c_t_2,
  '2c-t-7': _2c_t_7,
  '3c-p': _3c_p,
  '3c-e': _3c_e,
  '4-aco-det': _4_aco_det,
  '4-aco-met': _4_aco_met,
  '4-aco-dmt': _4_aco_dmt,
  '4-aco-dipt': _4_aco_dipt,
  '4-aco-mipt': _4_aco_mipt,
  '4-ho-det': _4_ho_det,
  '4-ho-dpt': _4_ho_dpt,
  '4-ho-met': _4_ho_met,
  '4-ho-dipt': _4_ho_dipt,
  '4-ho-ept': _4_ho_ept,
  '4-ho-mpt': _4_ho_mpt,
  '4-ho-mipt': _4_ho_mipt,
  '5-meo-dalt': _5_meo_dalt,
  '5-meo-dibf': _5_meo_dibf,
  '5-meo-dipt': _5_meo_dipt,
  '5-meo-dmt': _5_meo_dmt,
  '5-meo-mipt': _5_meo_mipt,
  '6-apb': _6_apb,
  'al-lad': al_lad,
  'ald-52': ald_52,
  'allylescaline': allylescaline,
  'ayahuasca': ayahuasca,
  'bufotenin': bufotenin,
  'bromo-dragonfly': bromo_dragonfly,
  'det': det,
  'dob': dob,
  'dmt': dmt,
  'doc': doc,
  'dom': dom,
  'doi': doi,
  'dpt': dpt,
  'dipt': dipt,
  'ept': ept,
  'eth-lad': eth_lad,
  'efavirenz': efavirenz,
  'escaline': escaline,
  'ibogaine': ibogaine,
  'lae-32': lae_32,
  'lsm-775': lsm_775,
  'lsa': lsa,
  'lsz': lsz,
  'lsd': lsd,
  'mpt': mpt,
  'met': met,
  'mda': mda,
  'methallylescaline': methallylescaline,
  'mescaline': mescaline,
  'mipt': mipt,
  'mipla': mipla,
  'pargy-lad': pargy_lad,
  'pro-lad': pro_lad,
  '2-aminoindane': _2_aminoindane,
  '2-fea': _2_fea,
  '2-fa': _2_fa,
  '2-fma': _2_fma,
  '3-4-ctmp': _3_4_ctmp,
  '3-fa': _3_fa,
  '3-fpm': _3_fpm,
  '3-fma': _3_fma,
  '3-fea': _3_fea,
  '3-mmc': _3_mmc,
  '4-fa': _4_fa,
  '4-fma': _4_fma,
  '4f-eph': _4f_eph,
  '4f-mph': _4f_mph,
  '5-apb': _5_apb,
  '6-apdb': _6_apdb,
  'a-php': a_php,
  'a-pvp': a_pvp,
  'adrafinil': adrafinil,
  'amphetamine': amphetamine,
  'armodafinil': armodafinil,
  'benzydamine': benzydamine,
  'bromantane': bromantane,
  'butylone': butylone,
  'caffeine': caffeine,
  'cyclazodone': cyclazodone,
  'cocaine': cocaine,
  'desoxypipradrol': desoxypipradrol,
  'dextroamphetamine': dextroamphetamine,
  'dichloropane': dichloropane,
  'eth-cat': eth_cat,
  'ephedrine': ephedrine,
  'ephylone': ephylone,
  'ethylphenidate': ethylphenidate,
  'ethylone': ethylone,
  'fenethylline': fenethylline,
  'hexedrone': hexedrone,
  'isopropylphenidate': isopropylphenidate,
  'kratom': kratom,
  'lisdexamfetamine': lisdexamfetamine,
  'mcpp': mcpp,
  'mdpv': mdpv,
  'mdma': mdma,
  'mephedrone': mephedrone,
  'methcathinone': methcathinone,
  'methamphetamine': methamphetamine,
  'methiopropamine': methiopropamine,
  'methylone': methylone,
  'methylnaphthidate': methylnaphthidate,
  'methylphenidate': methylphenidate,
  'mexedrone': mexedrone,
  'modafinil': modafinil,
  'n-methylbisfluoromodafinil': n_methylbisfluoromodafinil,
  'n-ethylhexedrone': n_ethylhexedrone,
  'nm-2-ai': nm_2_ai,
  'nep': nep,
  'nicotine': nicotine,
  'oxiracetam': oxiracetam,
  'pentedrone': pentedrone,
  'phenylpiracetam': phenylpiracetam,
  '1-4-butanediol': _1_4_butanediol,
  '2m2b': _2m2b,
  'alcohol': alcohol,
  'alprazolam': alprazolam,
  'baclofen': baclofen,
  'cake': cake,
  'carisoprodol': carisoprodol,
  'clonazepam': clonazepam,
  'clonidine': clonidine,
  'clonazolam': clonazolam,
  'deschloroetizolam': deschloroetizolam,
  'diazepam': diazepam,
  'diclazepam': diclazepam,
  'eszopiclone': eszopiclone,
  'etizolam': etizolam,
  'f-phenibut': f_phenibut,
  'flubromazepam': flubromazepam,
  'flualprazolam': flualprazolam,
  'flunitrazepam': flunitrazepam,
  'flubromazolam': flubromazolam,
  'flunitrazolam': flunitrazolam,
  'gbl': gbl,
  'ghb': ghb,
  'grayanotoxin': grayanotoxin,
  'gabapentin': gabapentin,
  'gaboxadol': gaboxadol,
  'lorazepam': lorazepam,
  'mephenaqualone': mephenaqualone,
  'methaqualone': methaqualone,
  'metizolam': metizolam,
  'midazolam': midazolam,
  'mirtazapine': mirtazapine,
  'nifoxipam': nifoxipam,
  'pentobarbital': pentobarbital,
  'phenobarbital': phenobarbital,
  '2-fluorodeschloroketamine': _2_fluorodeschloroketamine,
  '3-ho-pce': _3_ho_pce,
  '3-ho-pcp': _3_ho_pcp,
  '3-meo-pcmo': _3_meo_pcmo,
  '3-meo-pce': _3_meo_pce,
  '3-meo-pcp': _3_meo_pcp,
  '4-meo-pcp': _4_meo_pcp,
  'deschloroketamine': deschloroketamine,
  'dextromethorphan': dextromethorphan,
  'diphenidine': diphenidine,
  'ephenidine': ephenidine,
  'hxe': hxe,
  'ketamine': ketamine,
  'mxipr': mxipr,
  'memantine': memantine,
  'methoxetamine': methoxetamine,
  'methoxphenidine': methoxphenidine,
  'nitrous': nitrous,
  'o-pce': o_pce,
  'pce': pce,
  'pcp': pcp,
  '5-mapb': _5_mapb,
  'mdai': mdai,
  'mdea': mdea,
  'pma': pma,
  'pmma': pmma,
  '5f-akb48': _5f_akb48,
  '5f-pb-22': _5f_pb_22,
  'ab-fubinaca': ab_fubinaca,
  'apica': apica,
  'cannabidiol': cannabidiol,
  'jwh-018': jwh_018,
  'jwh-073': jwh_073,
  'acetylfentanyl': acetylfentanyl,
  'buprenorphine': buprenorphine,
  'codeine': codeine,
  'desomorphine': desomorphine,
  'dextropropoxyphene': dextropropoxyphene,
  'dihydrocodeine': dihydrocodeine,
  'ethylmorphine': ethylmorphine,
  'fentanyl': fentanyl,
  'hydrocodone': hydrocodone,
  'hydromorphone': hydromorphone,
  'heroin': heroin,
  'methadone': methadone,
  'morphine': morphine,
  'naloxone': naloxone,
  'o-desmethyltramadol': o_desmethyltramadol,
  'oxycodone': oxycodone,
  'oxymorphone': oxymorphone,
  'pethidine': pethidine,
  'datura': datura,
  'diphenhydramine': diphenhydramine,
  'myristicin': myristicin,
  '5-hydroxytryptophan': _5_hydroxytryptophan,
  'alpha-gpc': alpha_gpc,
  'aniracetam': aniracetam,
  'citicoline': citicoline,
  'choline-bitartrate': choline_bitartrate,
  'creatine': creatine,
  'coluracetam': coluracetam,
  'galantamine': galantamine,
  'meclofenoxate': meclofenoxate,
  'n-acetylcysteine': n_acetylcysteine,
  'omberacetam': omberacetam,
  'blue-lotus': blue_lotus,
  'bromazepam': bromazepam,
  'cannabis': cannabis
};

/**
 * Get a substance by its unique ID
 */
export function getSubstanceById(id: string): Substance | undefined {
  return substancesById[id];
}

/**
 * Get all substances in a specific category
 */
export function getSubstancesByCategory(category: string): Substance[] {
  return substancesByCategory[category] || [];
}

/**
 * Search substances by name, common names, aliases, or description
 */
export function searchSubstances(query: string): Substance[] {
  const lowerQuery = query.toLowerCase().trim();
  if (!lowerQuery) return [];
  
  return substances.filter(s =>
    s.name.toLowerCase().includes(lowerQuery) ||
    s.commonNames.some(n => n.toLowerCase().includes(lowerQuery)) ||
    s.aliases.some(a => a.toLowerCase().includes(lowerQuery)) ||
    s.description.toLowerCase().includes(lowerQuery)
  );
}

export function getAllSubstanceIds(): string[] {
  return substances.map(s => s.id);
}

export function getAllSubstanceNames(): string[] {
  return substances.map(s => s.name);
}

export function getSubstancesByRiskLevel(riskLevel: 'low' | 'moderate' | 'high' | 'very-high'): Substance[] {
  return substances.filter(s => s.riskLevel === riskLevel);
}

export function getSubstancesByRoute(route: string): Substance[] {
  return substances.filter(s => s.routes && s.routes.includes(route));
}

export function getSubstancesByInteraction(interaction: string): Substance[] {
  const lowerInteraction = interaction.toLowerCase();
  return substances.filter(s =>
    s.interactions.some(i => i.toLowerCase().includes(lowerInteraction))
  );
}

export function getSubstanceCount(): number {
  return substances.length;
}

export function getSubstanceCountByCategory(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const category of Object.keys(substancesByCategory)) {
    counts[category] = substancesByCategory[category].length;
  }
  return counts;
}

// Category constants for convenience
export const CATEGORY_IDS = {
  CANNABINOIDS: 'cannabinoids' as SubstanceCategory,
  DELIRIANTS: 'deliriants' as SubstanceCategory,
  DEPRESSANTS: 'depressants' as SubstanceCategory,
  DISSOCIATIVES: 'dissociatives' as SubstanceCategory,
  EMPATHOGENS: 'empathogens' as SubstanceCategory,
  HALLUCINOGENS: 'hallucinogens' as SubstanceCategory,
  NOOTROPICS: 'nootropics' as SubstanceCategory,
  OPIOIDS: 'opioids' as SubstanceCategory,
  OTHER: 'other' as SubstanceCategory,
  STIMULANTS: 'stimulants' as SubstanceCategory
};

// Risk level constants
export const RISK_LEVELS = {
  LOW: 'low' as const,
  MODERATE: 'moderate' as const,
  HIGH: 'high' as const,
  VERY_HIGH: 'very-high' as const
};
