// Auto-generated from substances.txt
import type { Substance } from '../types';

// Substance Data
// Name: LSD
// ID: lsd
// Categories: hallucinogens
// Class: Lysergamides

export const lsd: Substance = 
{
  "id": "lsd",
  "name": "LSD",
  "commonNames": [
    "Lysergamides"
  ],
  "categories": [
    "hallucinogens"
  ],
  "class": "Lysergamides",
  "description": "It is perhaps the most researched and culturally influential psychedelic substance, as well as the prototypal lysergamide. In the 1950s, it was widely distributed by Sandoz as an experimental drug for psychotherapy and scientific research; during this era, it provoked considerable interest from the intellectual establishment and was even the subject of a clandestine investigation by the U.S. Central Intelligence Agency (CIA) for potential applications in \"mind control\". Recreational LSD use became a central, highly-visible aspect of the 1960s youth counterculture movement, eventually paving the way for international prohibition in 1971. Today, illicit recreational use remains widespread and it is associated in popular culture with the counterculture and rave scenes. Unlike most highly prohibited substances, LSD has not been proven to be physiologically toxic or addictive.",
  "effects": {
    "positive": [
      "Neurogenesis",
      "Stimulation - LSD is usually described as very energetic and stimulating without being forced. For example, it tends to encourage physical activities such as walking, climbing, or dancing. <p>In comparison, other common psychedelics such as psilocybin or LSA are generally sedating and sedentary.",
      "Spontaneous bodily sensations - The \"body high\" of LSD behaves as a euphoric, fast-moving, sharp and location specific or generalized tingling sensation.",
      "Physical euphoria - A unique form of physical euphoria may occur at certain points of the trip. However, it is limited and inconsistent compared to the effect of entactogens or opioids, and can just as easily manifest as physical discomfort without any apparent reason.",
      "Perception of bodily lightness - The stimulation and energy LSD produces can cause the user to feel as if they are moving weightlessly.",
      "Tactile enhancement - Feelings of enhanced tactile sensations are consistently present at moderate levels throughout most LSD trips.",
      "Changes in felt bodily form - This effect is often accompanied by a sense of warmth or unity and usually near the peak of the experience. Users can feel as if they are physically part of or conjoined with other objects.",
      "Bodily control enhancement",
      "Stamina enhancement - The user's stamina for physical activities may be enhanced. Some users have also reported using small doses to improve athletic performance. However, this effect is generally mild compared to the effect of stimulants.",
      "Colour enhancement - Compared to other psychedelics, this effect is often reported to be brighter and more \"radiant\" in character.",
      "Machinescapes - A rare effect that typically only occurs at very strong to heavy doses, and not as consistently as with certain psychedelics such as DMT, psilocybin mushrooms, 2C-P, and atypical psychedelics like salvia.",
      "Analysis enhancement - Some users report gaining the ability to analyze situations in novel and relatively objective ways. It is not clear if this is actually the case, or just a feeling generated by the substance.",
      "Cognitive euphoria - Cognitive euphoria is limited and inconsistent compared to that of MDMA, cocaine, and opioids. Unlike the aforementioned substances, mental euphoria on psychedelics is \"unforced\", meaning it requires a pre-existing positive emotional state.",
      "Euthymia - This effect manifests itself acutely for all classical psychedelics when one to three doses are combined with a psychotherapy treatment program. When comparing meta analyses, psychedelic psychotherapy greatly outperforms \"gold standard\" treatments for several mental health problems.",
      "Creativity enhancement - LSD is well-known for its ability to enhance creativity and out-of-the-box thinking. A large number of artists, musicians, scientists, and other intellectuals have used it, dating to the 1950s.",
      "Novelty enhancement - Very prominent on LSD compared to other substances.",
      "Focus enhancement - Occurs mostly on low or threshold dosages and feels less forced or sharp than it does with stimulants.",
      "Immersion enhancement - Very prominent on LSD compared to other substances, second only to dissociative immersion enhancement.",
      "Personal meaning enhancement - The user may feel as if their experience has special meaning, which may or may not last after the trip. Appears to depend on the user's set and setting.",
      "Emotion enhancement - The user's ability to experience emotion may be strongly enhanced. This is thought to contribute to its therapeutic effect. Consequently, it is advised to not take LSD when in a low or unstable mood and to follow the principles of set and setting.",
      "Empathy, affection and sociability enhancement - Can be prominent but also unreliable compared to MDMA. More dose-dependent; higher doses are more likely to cause introspection and social withdrawal.",
      "Increased libido - Generally inconsistent compared to stimulants and cannabis. Mild to moderate when it does occur.",
      "Increased music appreciation - Extremely prominent for many users. Likely a part of its therapeutic effect. Sublime or mystical experiences on LSD are often linked to music.",
      "Increased sense of humor - Very common on LSD, particularly during the come up and peak phases. Users report suddenly finding mundane situations and actions inexplicably hilarious.",
      "Laughter fits - Laughter fits are common, particularly during the come up phase. It can manifest as uncontrollable giggles and laughter that can form a feedback loop if around others who are also under the influence.",
      "Motivation enhancement - LSD produces stimulant-like motivation enhancement at low and microdoses, although in a much less prominent or reliable manner.",
      "Suggestibility enhancement - Suggestibility to external influences may be strongly enhanced. While potentially beneficial for psychotherapy, this property can be abused by nefarious individuals (e.g. cult leaders). Users are advised to be discerning about who they take LSD with.",
      "Thought connectivity - A signature effect. Thoughts may feel more fluid and interconnected than usual. May occur alongside conceptual thinking and creativity enhancement.",
      "Wakefulness - Users report that it is difficult or impossible to go to sleep for up to 10 hours (or more) after LSD ingestion.",
      "Addiction suppression - Some research suggests LSD can be used to treat addiction. Anecdotally, many users report that psychedelics are helpful for this purpose.",
      "Auditory enhancement - Some users report an enhanced sense of hearing on LSD. However, there is currently no clinical evidence supporting this claim.",
      "Synaesthesia - True synesthesia is rare and non-reproducible, although users often describe the feeling of being able to \"hear colors\" and \"see sounds\". Increasing the dosage can increase the likelihood of occurrence, but seems to primarily occur in those who are already predisposed to synesthetic states.",
      "Existential self-realization",
      "Spirituality enhancement",
      "Unity and interconnectedness"
    ],
    "neutral": [
      "Visual acuity enhancement",
      "Pattern recognition enhancement",
      "Magnification",
      "Frame rate enhancement",
      "Drifting (melting, breathing, morphing and flowing) - Compared to other psychedelics, this effect can be described as highly detailed yet cartoon-like in its appearance. The distortions are slow and smooth in motion and fleeting in their appearance.",
      "Colour shifting",
      "Tracers",
      "After images",
      "Depth perception distortions",
      "Environmental patterning",
      "Perspective distortions",
      "Recursion",
      "Symmetrical texture repetition",
      "Scenery slicing",
      "Transformations",
      "Internal hallucination (autonomous entities; settings, sceneries, and landscapes; perspective hallucinations and scenarios and plots) - Although some users report that LSD is capable of producing hallucinatory states with the same intensity and vividness as psilocybin mushrooms or DMT, it is much rarer and less consistent. While traditional psychedelics such as LSA, ayahuasca and mescaline will induce internal hallucinations near consistently at level 5 geometry and above, some users claim that LSD tends to go straight into Level 8A visual geometry. <p>This lack of consistently induced hallucinatory breakthroughs means that for most, LSD is relatively limited in depth, at doses that do not come with excessive side effects.",
      "External hallucination (autonomous entities; settings, sceneries, and landscapes; perspective hallucinations and scenarios and plots)",
      "Conceptual thinking - A signature effect. LSD may allow the user to bypass normal cognitive patterns (and their associated limitations). Manifests as lateral or abstract thinking patterns.",
      "Multiple thought streams",
      "Simultaneous emotions",
      "Thought acceleration",
      "Time distortion - A signature effect. The user's perception of time may be strongly altered. Typically takes the form of time dilation, or the experience of time slowing down and passing much slower than it does while sober.",
      "Auditory distortion - Sounds may appear \"tinny\" or \"alien\". More likely at higher doses.  Certain subjective reports mention flanging, delays/echoing, reverb-like effects, similar to those found in music."
    ],
    "negative": [
      "Pain relief - LSD can greatly reduce or distort the perception of pain. This is likely due to a variety of factors as the hallucinogenic effects mean that pain can be interpreted as a different sensation (i.e. a tickling sensation from a painful stimulus). <p>LSD also possesses potent anti-inflammatory properties that likely contribute to this effect.",
      "Temperature regulation suppression - LSD appears to cause the body to lose some of its ability to regulate its temperature. While usually harmless, users should be careful when taking LSD in conditions of extreme hot or cold.",
      "Increased bodily temperature  - Potentially dangerous states of overheating have been reported to occur in certain conditions, particularly with higher doses due to the fact that LSD raises body serotonin.",
      "Nausea - Mild nausea is occasionally reported on moderate to high doses and either passes after the user vomits or gradually fades by itself as the peak sets in.",
      "Appetite suppression - LSD can suppress appetite in a manner similar to (although not as strong as) stimulants, especially for fatty foods.",
      "Dehydration - Mild to moderate dehydration may occur. Not as extreme as with stimulants or opioids.",
      "Difficulty urinating",
      "Increased blood pressure - Very rare but can occur in those who are predisposed to them, particularly while in physically taxing conditions such as being dehydrated, undernourished, overheated, or fatigued.",
      "Teeth grinding - Mild to moderate. Not as intense as on MDMA.",
      "Vasoconstriction - Dose-dependent, but weaker compared to stimulants, 25x-NBOMe, or DOx. Some users report feeling cold, especially in the extremities.",
      "Anxiety & Paranoia - Not typically observed at low to common doses and are less likely to occur when the basic rules of set and setting are taken into account.",
      "Introspection - Present at most doses. May occur alongside personal bias suppression.",
      "Personal bias suppression - The user may feel they have the ability to analyze their lives or relationships in a more objective way. It is not clear if this is actually the case, or just a feeling generated by the substance.",
      "Delusion - Mild delusions can occur at common doses. Serious, persisting delusions are typically limited to higher doses or individual susceptibility.",
      "Déjà vu - Unreliable and usually at higher doses. May indicate an overdose and the beginning of delusions and psychosis.",
      "Memory suppression - Present at all dose levels past low-common. Stronger than phenethylamines like mescaline or 2C-B but weaker than tryptamines like psilocybin or DMT.",
      "Ego loss - A signature effect. May be accompanied by euphoria or dysphoria depending on set and setting. Also accompanied by time distortion and potentially thought loops.",
      "Ego replacement - Ego replacement is very rare and occurs in an unpredictable manner. This effect usually coincides with delusions and may indicate the beginnings of psychosis. It is more likely to occur with high doses.",
      "Personality regression - True personality regression on LSD is very rare. More commonly, it takes the milder form of the user having strong feelings of early childhood, including repressed memories.",
      "Thought loops - Typically occurs at higher doses, and at the peak of the experience. Often accompanied by ego loss. This effect may become exacerbated or triggered by cannabis or stimulants.",
      "Auditory hallucination - Typically present at higher doses. Not as common as visual hallucinations, but may occur alongside them."
    ]
  },
  "routeData": {
    "sublingual": {
      "dosage": {
        "threshold": "15µg",
        "light": "15-75µg",
        "common": "75-150µg",
        "strong": "150-300µg",
        "heavy": "300µg"
      },
      "duration": {
        "onset": "15-30 minutes",
        "comeup": "45-90 minutes",
        "peak": "3-5 hours",
        "offset": "3-5 hours",
        "total": "8-12 hours"
      },
      "notes": "Afterglow: 12-48 hours"
    }
  },
  "interactions": [
    "Lithium",
    "Tramadol",
    "Deliriants",
    "Tricyclic antidepressants",
    "Ritonavir"
  ],
  "harmReduction": [
    "extremely low toxicity relative to dose"
  ],
  "legality": "Legal status varies by jurisdiction. Check local laws.",
  "chemistry": {
    "formula": "Unknown",
    "molecularWeight": "Unknown",
    "class": "Lysergamides"
  },
  "history": "Information not available in source data.",
  "afterEffects": "See route data for afterglow information.",
  "riskLevel": "low",
  "aliases": [
    "Lysergamides"
  ]
};